import type { Locale } from "@/lib/i18n"

export type ChangelogKind = "added" | "fixed" | "improved"

export type ChangelogEntry = {
  id: string
  date: string
  kind: ChangelogKind
  en: string
  tc: string
  sc: string
}

export const CHANGELOG: readonly ChangelogEntry[] = [
  {
    id: "2026-10-10-charger-card-align",
    date: "2026-10-10",
    kind: "fixed",
    en: "The free count on a charger card lines up with the plug counts.",
    tc: "充電站卡片的空置數目與插頭數目對齊。",
    sc: "充电站卡片的空置数目与插头数目对齐。",
  },
  {
    id: "2026-10-10-charger-card-free",
    date: "2026-10-10",
    kind: "fixed",
    en: "A charger card shows how many plugs are free, the same number as its pin.",
    tc: "充電站卡片顯示與標籤相同的空置數目。",
    sc: "充电站卡片显示与标签相同的空置数目。",
  },
  {
    id: "2026-10-10-share",
    date: "2026-10-10",
    kind: "added",
    en: "The board can share its address.",
    tc: "可以分享這個版面的網址。",
    sc: "可以分享这个版面的网址。",
  },
  {
    id: "2026-10-09-journey-name",
    date: "2026-10-09",
    kind: "fixed",
    en: "A Chinese journey card names the destination in Chinese.",
    tc: "中文行車時間卡以中文顯示目的地。",
    sc: "中文行车时间卡以中文显示目的地。",
  },
  {
    id: "2026-10-09-other-journey-minutes",
    date: "2026-10-09",
    kind: "added",
    en: "Journey minutes for the other tunnels and roads appear on the sign that publishes them. The three harbour times stay on the bar.",
    tc: "其他隧道和道路的行車時間，顯示在公布該時間的標誌上。三條過海時間仍留在橫條上。",
    sc: "其他隧道和道路的行车时间，显示在公布该时间的标志上。三条过海时间仍留在横条上。",
  },
  {
    id: "2026-10-08-intel-layer",
    date: "2026-10-08",
    kind: "improved",
    en: "Clicking an intel item turns on its layer. If Only is showing a different layer, Only turns off and that layer turns on beside it.",
    tc: "點情報項目會打開它所屬的圖層。若「只看」正顯示另一圖層，「只看」會放開，並一併打開該圖層。",
    sc: "点情报项目会打开它所属的图层。若「只看」正显示另一图层，「只看」会放开，并一并打开该图层。",
  },
  {
    id: "2026-10-08-bus-credits",
    date: "2026-10-08",
    kind: "fixed",
    en: "KMB, LWB, Citybus, NLB, HKKF, and MTR use their short names.",
    tc: "署名用簡稱：KMB、LWB、Citybus、NLB、HKKF 和 MTR。",
    sc: "署名用简称：KMB、LWB、Citybus、NLB、HKKF 和 MTR。",
  },
  {
    id: "2026-10-08-map-credits",
    date: "2026-10-08",
    kind: "fixed",
    en: "Each credit on the map is named once. OpenStreetMap no longer repeats, and Sun Ferry, Hong Kong and Kowloon Ferry, the Star Ferry, and Fortune Ferry are named.",
    tc: "地圖上每個來源只署名一次。OpenStreetMap 不再重複，新渡輪、港九小輪、天星小輪和富裕小輪都有署名。",
    sc: "地图上每个来源只署名一次。OpenStreetMap 不再重复，新渡轮、港九小轮、天星小轮和富裕小轮都有署名。",
  },
  {
    id: "2026-10-08-layers-beside-card",
    date: "2026-10-08",
    kind: "fixed",
    en: "The layer list stays beside the intel card on a wide screen, and every layer name remains visible.",
    tc: "寬螢幕上，圖層名單留在情報卡旁邊，每個圖層名稱都看得到。",
    sc: "宽屏幕上，图层名单留在情报卡旁边，每个图层名称都看得到。",
  },
  {
    id: "2026-10-07-fold-motion",
    date: "2026-10-07",
    kind: "improved",
    en: "Opening and closing a control moves. The mark turns, and the panel eases in the same way each time.",
    tc: "展開和收合時會有動作。記號轉動，面板每次都以同一方式緩緩打開。",
    sc: "展开和收合时会有动作。记号转动，面板每次都以同一方式缓缓打开。",
  },
  {
    id: "2026-10-07-park-dots",
    date: "2026-10-07",
    kind: "fixed",
    en: "Car parks and motorcycle parks show together as dots when the map is zoomed out. The counts stay on the closer view.",
    tc: "地圖縮小時，停車場和電單車泊位一起以點顯示。空位數字留在較近的畫面。",
    sc: "地图缩小时，停车场和电单车泊位一起以点显示。空位数字留在较近的画面。",
  },
  {
    id: "2026-10-07-place-first-reading",
    date: "2026-10-07",
    kind: "fixed",
    en: "Car parks and motorcycle parks appear the first time that layer is turned on.",
    tc: "第一次打開停車場或電單車圖層時，車位會出現。",
    sc: "第一次打开停车场或电单车图层时，车位会出现。",
  },
  {
    id: "2026-10-07-speed-reading-race",
    date: "2026-10-07",
    kind: "fixed",
    en: "A speed reading that went out before the official class does not stay up for a full minute, and a refresh that starts while a reading is still arriving is kept.",
    tc: "未帶到官方等級的車速讀數不會停一整分鐘。讀數還在途中時開始的下一次更新會保留。",
    sc: "未带到官方等级的车速读数不会停一整分钟。读数还在途中时开始的下一次更新会保留。",
  },
  {
    id: "2026-10-07-speed-with-the-board",
    date: "2026-10-07",
    kind: "fixed",
    en: "Speed colours, the network speed, and the slow roads appear with the rest of the board.",
    tc: "道路顏色、路網車速和緩慢路段與其他讀數一起出現。",
    sc: "道路颜色、路网车速和缓慢路段与其他读数一起出现。",
  },
  {
    id: "2026-10-07-fold-marks",
    date: "2026-10-07",
    kind: "improved",
    en: "The intel card, the harbour bar, and the crossing list use the same mark as Layers. A closed control points up. An open one points down.",
    tc: "情報、過海列和口岸清單用與圖層相同的記號。收合時指向上，展開時指向下。",
    sc: "情报、过海列和口岸清单用与图层相同的记号。收合时指向上，展开时指向下。",
  },
  {
    id: "2026-10-07-layer-bar-fold",
    date: "2026-10-07",
    kind: "improved",
    en: "Only, All, and Replay fold away with the layer names. The Layers chip has a mark, so it is clear it opens.",
    tc: "只看、全部和重播會跟圖層名稱一起收起。圖層有記號，看得出可以打開。",
    sc: "只看、全部和重播会跟图层名称一起收起。图层有记号，看得出可以打开。",
  },
  {
    id: "2026-10-07-phone-intel",
    date: "2026-10-07",
    kind: "improved",
    en: "A phone starts with the intel card on one line. Opening or hiding it stays for the next visit.",
    tc: "手機一打開，情報先收成一行。之後打開或收起，下次會保持。",
    sc: "手机一打开，情报先收成一行。之后打开或收起，下次会保持。",
  },
  {
    id: "2026-10-07-layer-collapse",
    date: "2026-10-07",
    kind: "added",
    en: "The layer names can be hidden. A phone starts with them hidden so the map stays clear.",
    tc: "圖層名稱可以收起。手機一打開就先收起，地圖不會被擋住。",
    sc: "图层名称可以收起。手机一打开就先收起，地图不会被挡住。",
  },
  {
    id: "2026-10-07-only-second-layer",
    date: "2026-10-07",
    kind: "fixed",
    en: "Choosing a second layer leaves Only, and both layers stay on.",
    tc: "再選一層會離開「只看」，兩層一起顯示。",
    sc: "再选一层会离开「只看」，两层一起显示。",
  },
  {
    id: "2026-10-07-minibus-names",
    date: "2026-10-07",
    kind: "fixed",
    en: "Green minibus stops appear with the other bus stops. Names start at the same zoom.",
    tc: "綠色專線小巴車站與其他巴士同時出現，站名也在同一縮放出現。",
    sc: "绿色专线小巴车站与其他巴士同时出现，站名也在同一缩放出现。",
  },
  {
    id: "2026-10-07-terminus-trains",
    date: "2026-10-07",
    kind: "fixed",
    en: "A train that has not left stays at that station. It no longer rolls down the line before the published time.",
    tc: "未開出的列車留在該站，不會在公布時間之前沿路開出。",
    sc: "未开出的列车留在该站，不会在公布时间之前沿路开出。",
  },
  {
    id: "2026-10-06-harbour-pins",
    date: "2026-10-06",
    kind: "improved",
    en: "The harbour view keeps the live road colours. Cameras and free-count pins return once the map is closer.",
    tc: "海港全景只保留路面車速。快拍和空位數目會在地圖再近一些時出現。",
    sc: "海港全景只保留路面车速。快拍和空位数目会在地图再近一些时出现。",
  },
  {
    id: "2026-10-06-charger-place-district",
    date: "2026-10-06",
    kind: "added",
    en: "A charger card shows the district.",
    tc: "充電站卡片顯示地區。",
    sc: "充电站卡片显示地区。",
  },
  {
    id: "2026-10-06-charger-clock",
    date: "2026-10-06",
    kind: "improved",
    en: "A charger count refreshes with the car park and meter counts.",
    tc: "充電站空置數目與停車場和咪錶一起更新。",
    sc: "充电站空置数目与停车场和咪表一起更新。",
  },
  {
    id: "2026-10-06-charger-availability",
    date: "2026-10-06",
    kind: "added",
    en: "A charger shows how many plugs are free when the public list publishes that number.",
    tc: "充電站在公開名單有公布時顯示空置插頭數目。",
    sc: "充电站在公开名单有公布时显示空置插头数目。",
  },
  {
    id: "2026-10-06-parking-ev",
    date: "2026-10-06",
    kind: "added",
    en: "A car park card shows how many electric-vehicle spaces are free when that number is published.",
    tc: "停車場卡片在有公布時顯示電動車空位數目。",
    sc: "停车场卡片在有公布时显示电动车空位数目。",
  },
  {
    id: "2026-10-06-onestop-parks",
    date: "2026-10-06",
    kind: "added",
    en: "Kowloon East car parks, including Amoy Plaza and Telford Plaza, show how many spaces are free. A closed car park is marked closed.",
    tc: "九龍東的停車場，包括淘大和德福，顯示空位數目。關閉的場會寫明關閉。",
    sc: "九龙东的停车场，包括淘大和德福，显示空位数目。关闭的场会写明关闭。",
  },
  {
    id: "2026-10-06-clp-chargers",
    date: "2026-10-06",
    kind: "added",
    en: "A CLP charger shows how many plugs are free when CLP publishes that number.",
    tc: "中電充電站在中電有公布時顯示空置插頭數目。",
    sc: "中电充电站在中电有公布时显示空置插头数目。",
  },
  {
    id: "2026-10-06-motorcycle-counts",
    date: "2026-10-06",
    kind: "fixed",
    en: "A motorcycle park shows how many spaces are free.",
    tc: "電單車停車場顯示空位數目。",
    sc: "电单车停车场显示空位数目。",
  },
  {
    id: "2026-10-06-meter-kind-colour",
    date: "2026-10-06",
    kind: "improved",
    en: "Goods-vehicle and coach meters are magenta. Private-car and light-van meters stay blue.",
    tc: "貨車和旅遊巴咪錶是洋紅色。私家車和輕型貨車咪錶仍然是藍色。",
    sc: "货车和旅游巴咪表是洋红色。私家车和轻型货车咪表仍然是蓝色。",
  },
  {
    id: "2026-10-06-count-sooner",
    date: "2026-10-06",
    kind: "improved",
    en: "Every car park and meter on the map shows how many spaces are free.",
    tc: "地圖上每個停車場和咪錶都顯示空位數目。",
    sc: "地图上每个停车场和咪表都显示空位数目。",
  },
  {
    id: "2026-10-06-vacancy-on-the-pin",
    date: "2026-10-06",
    kind: "improved",
    en: "A car park and a meter show how many spaces are free, beside the name.",
    tc: "停車場和咪錶在名字旁寫明空位數目。",
    sc: "停车场和咪表在名字旁写明空位数目。",
  },
  {
    id: "2026-10-06-real-rails",
    date: "2026-10-06",
    kind: "improved",
    en: "MTR and light-rail trains follow the real rails.",
    tc: "港鐵和輕鐵列車沿著真正的路軌行走。",
    sc: "港铁和轻铁列车沿着真正的路轨行走。",
  },
  {
    id: "2026-10-06-gwat-card",
    date: "2026-10-06",
    kind: "fixed",
    en: "A street-bay card says the spaces are motorcycle bays.",
    tc: "骨位卡片寫明是電單車骨位。",
    sc: "骨位卡片写明是电单车骨位。",
  },
  {
    id: "2026-10-06-gwat-name",
    date: "2026-10-06",
    kind: "improved",
    en: "The street-bay switch is named 電單車骨位.",
    tc: "路邊劃位的開關叫做電單車骨位。",
    sc: "路边划位的开关叫做电单车骨位。",
  },
  {
    id: "2026-10-06-kerb-bays",
    date: "2026-10-06",
    kind: "added",
    en: "Painted motorcycle bays can be switched on. Each pin is a row, and the number is how many bays are painted.",
    tc: "路邊電單車位可以打開。每個標記是一列車位，數目是劃了多少個。",
    sc: "路边电单车位可以打开。每个标记是一列车位，数目是划了多少个。",
  },
  {
    id: "2026-10-06-motorcycle-parks",
    date: "2026-10-06",
    kind: "added",
    en: "Car parks that publish motorcycle spaces appear on their own. The label shows how many are free, and the same park is not drawn twice.",
    tc: "有公布電單車空位的停車場會單獨顯示。標記寫著剩餘數目，同一個場不會畫兩次。",
    sc: "有公布电单车空位的停车场会单独显示。标记写着剩余数目，同一个场不会画两次。",
  },
  {
    id: "2026-10-06-charger-district",
    date: "2026-10-06",
    kind: "improved",
    en: "An English charger card shows the district in English.",
    tc: "英文充電樁卡片以英文顯示地區。",
    sc: "英文充电桩卡片以英文显示地区。",
  },
  {
    id: "2026-10-06-charger-in-park",
    date: "2026-10-06",
    kind: "fixed",
    en: "A charger inside a car park no longer draws a second dot. The plug counts are on the car park card.",
    tc: "停車場裡的充電樁不再多畫一個點。插頭數目寫在停車場卡片上。",
    sc: "停车场里的充电桩不再多画一个点。插头数目写在停车场卡片上。",
  },
  {
    id: "2026-10-06-public-chargers",
    date: "2026-10-06",
    kind: "added",
    en: "Public chargers from the June 2026 government list can be switched on. Each pin shows the plug counts from that list.",
    tc: "2026年6月的公共充電樁可以打開。每個標記顯示該名單上的插頭數目。",
    sc: "2026年6月的公共充电桩可以打开。每个标记显示该名单上的插头数目。",
  },
  {
    id: "2026-10-06-shared-station",
    date: "2026-10-06",
    kind: "fixed",
    en: "A train that is still minutes away is no longer drawn on a different line that is already at the station.",
    tc: "尚未到站的列車，不會再疊在另一條線已經在站上的列車上面。",
    sc: "尚未到站的列车，不会再叠在另一条线已经在站上的列车上面。",
  },
  {
    id: "2026-10-06-track-gap",
    date: "2026-10-06",
    kind: "fixed",
    en: "Two trains on a bend keep separate markers while they are still apart along the track.",
    tc: "彎路上的兩班列車，只要沿路仍分開，就會各自顯示。",
    sc: "弯路上的两班列车，只要沿路仍分开，就会各自显示。",
  },
  {
    id: "2026-10-06-train-gap",
    date: "2026-10-06",
    kind: "fixed",
    en: "Trains with different arrival times no longer sit on the same spot and move as one.",
    tc: "到站時間不同的列車，不會再疊在同一點並以同一速度前進。",
    sc: "到站时间不同的列车，不会再叠在同一点并以同一速度前进。",
  },
  {
    id: "2026-10-06-vehicle-labels",
    date: "2026-10-06",
    kind: "improved",
    en: "Train and ferry names appear before the street view, and each one keeps its name while it moves.",
    tc: "列車和渡輪名稱在街景之前就會出現，行駛時名稱一直留在車上。",
    sc: "列车和渡轮名称在街景之前就会出现，行驶时名称一直留在车上。",
  },
  {
    id: "2026-10-05-layer-tap",
    date: "2026-10-05",
    kind: "fixed",
    en: "On a phone, tapping a layer name selects that layer.",
    tc: "在手機上，點選圖層名稱會選中該層。",
    sc: "在手机上，点选图层名称会选中该层。",
  },
  {
    id: "2026-10-05-iphone-marquee",
    date: "2026-10-05",
    kind: "fixed",
    en: "The headline strip scrolls on iPhone Safari.",
    tc: "iPhone Safari 上，情報條會捲動。",
    sc: "iPhone Safari 上，情报条会卷动。",
  },
  {
    id: "2026-10-05-only-wide",
    date: "2026-10-05",
    kind: "improved",
    en: "With 「Only」 on, each layer shows more pins from farther out. KMB keeps 160 stops, Citybus 200, green minibuses 160, New Lantao Bus 120, and MTR buses 240.",
    tc: "開啟「只看」後，每一層在更遠的地圖多顯示一些點。九巴 160 個站，城巴 200 個，綠色專線小巴 160 個，嶼巴 120 個，港鐵巴士 240 個。",
    sc: "开启「只看」后，每一层在更远的地图多显示一些点。九巴 160 个站，城巴 200 个，绿色专线小巴 160 个，屿巴 120 个，港铁巴士 240 个。",
  },
  {
    id: "2026-10-05-camera-zoom",
    date: "2026-10-05",
    kind: "fixed",
    en: "With 「Only」 on, cameras and car parks stay on the map when you zoom out.",
    tc: "開啟「只看」後，拉遠地圖，快拍和停車場仍然顯示。",
    sc: "开启「只看」后，拉远地图，快拍和停车场仍然显示。",
  },
  {
    id: "2026-10-05-camera-icon",
    date: "2026-10-05",
    kind: "improved",
    en: "A camera on the map is drawn as a camera, with the lens pointing the way it faces.",
    tc: "地圖上的快拍改為相機圖示，鏡頭指向拍攝方向。",
    sc: "地图上的快拍改为相机图示，镜头指向拍摄方向。",
  },
  {
    id: "2026-10-05-keep-left",
    date: "2026-10-05",
    kind: "fixed",
    en: "On a divided road, the speed dots travel on the left side.",
    tc: "分隔行車路上，車速點改為靠左行駛。",
    sc: "分隔行车路上，车速点改为靠左行驶。",
  },
  {
    id: "2026-10-05-meter-time",
    date: "2026-10-05",
    kind: "improved",
    en: "A meter card says the space has been vacant or occupied since that time.",
    tc: "咪錶卡片寫明車位由該時間起空置或佔用。",
    sc: "咪表卡片写明车位由该时间起空置或占用。",
  },
  {
    id: "2026-10-05-meters",
    date: "2026-10-05",
    kind: "added",
    en: "Nearby parking meters show whether a space is vacant. The map keeps to the nearest 40 poles.",
    tc: "附近咪錶會顯示有沒有空位。地圖只保留最近的 40 支咪錶。",
    sc: "附近咪表会显示有没有空位。地图只保留最近的 40 支咪表。",
  },
  {
    id: "2026-10-05-all-layers",
    date: "2026-10-05",
    kind: "added",
    en: "「All」 turns every layer on.",
    tc: "「全部」會打開每一層。",
    sc: "「全部」会打开每一层。",
  },
  {
    id: "2026-10-05-mtr-bus",
    date: "2026-10-05",
    kind: "added",
    en: "MTR buses appear at their stops, including K51 and K51A at Fu Tai. Opening a stop shows the published minutes.",
    tc: "港鐵巴士會在車站出現，包括富泰的 K51 和 K51A。打開車站，會顯示已公布的分鐘。",
    sc: "港铁巴士会在车站出现，包括富泰的 K51 和 K51A。打开车站，会显示已公布的分钟。",
  },
  {
    id: "2026-10-05-locate",
    date: "2026-10-05",
    kind: "added",
    en: "The map can mark where you are when you ask it.",
    tc: "按下定位，地圖會標出你的位置。",
    sc: "按下定位，地图会标出你的位置。",
  },
  {
    id: "2026-10-05-parking-time",
    date: "2026-10-05",
    kind: "improved",
    en: "A car park card shows the time the Transport Department published the spaces.",
    tc: "停車場卡片會顯示運輸署公布空位的時間。",
    sc: "停车场卡片会显示运输署公布空位的时间。",
  },
  {
    id: "2026-10-05-only-one",
    date: "2026-10-05",
    kind: "fixed",
    en: "「Only」 keeps a single layer. Choosing another layer switches to that one, and a quieter layer such as car parks shows from the city view.",
    tc: "「只看」只留一層。再選另一層，就換成該層。停車場這類較疏的圖層，在城市比例就會顯示。",
    sc: "「只看」只留一层。再选另一层，就换成该层。停车场这类较疏的图层，在城市比例就会显示。",
  },
  {
    id: "2026-10-05-overview-follow",
    date: "2026-10-05",
    kind: "fixed",
    en: "With 「Only」 on, moving the city view loads the pins for the place you are looking at. New Lantao Bus shows from the harbour when it is the only layer.",
    tc: "開啟「只看」後，在城市比例移動地圖，會載入你看着的位置的標記。「只看」嶼巴時，從海港也能找到車站。",
    sc: "开启「只看」后，在城市比例移动地图，会载入你看着的位置的标记。「只看」屿巴时，从海港也能找到车站。",
  },
  {
    id: "2026-10-05-pin-reach",
    date: "2026-10-05",
    kind: "fixed",
    en: "Stop and car park pins stay on the streets you can see when you zoom in.",
    tc: "拉近地圖時，畫面內的車站和停車場標記不會消失。",
    sc: "拉近地图时，画面内的车站和停车场标记不会消失。",
  },
  {
    id: "2026-10-05-parking-zoom",
    date: "2026-10-05",
    kind: "fixed",
    en: "With only car parks on, the pins stay on the map as you zoom in.",
    tc: "「只看」停車場時，拉近地圖，停車場標記仍然留在畫面上。",
    sc: "「只看」停车场时，拉近地图，停车场标记仍然留在画面上。",
  },
  {
    id: "2026-10-05-solo-zoom",
    date: "2026-10-05",
    kind: "improved",
    en: "With 「Only」 on, a quieter layer such as car parks or minibuses appears from farther away. KMB stays close in, because those stops cover the map.",
    tc: "開啟「只看」後，停車場或小巴等較疏的圖層會在較遠的比例顯示。九巴站多，仍然要拉近才顯示。",
    sc: "开启「只看」后，停车场或小巴等较疏的图层会在较远的比例显示。九巴站多，仍然要拉近才显示。",
  },
  {
    id: "2026-10-05-only-layer",
    date: "2026-10-05",
    kind: "added",
    en: "Choose 「Only」, then a layer, to leave just that layer on the map.",
    tc: "先按「只看」，再選一層，地圖就只留該層。",
    sc: "先按「只看」，再选一层，地图就只留该层。",
  },
  {
    id: "2026-10-05-parking",
    date: "2026-10-05",
    kind: "added",
    en: "Car parks appear when the map is close. Opening one shows the published spaces.",
    tc: "地圖拉近後會顯示停車場。打開一個，會顯示已公布的空位。",
    sc: "地图拉近后会显示停车场。打开一个，会显示已公布的空位。",
  },
  {
    id: "2026-10-04-title",
    date: "2026-10-04",
    kind: "improved",
    en: "The browser tab title is 香港智慧城市交通情報網 by Keith Li.",
    tc: "瀏覽器分頁標題是香港智慧城市交通情報網 by Keith Li。",
    sc: "浏览器分页标题是香港智慧城市交通情报网 by Keith Li。",
  },
  {
    id: "2026-10-04-remember",
    date: "2026-10-04",
    kind: "added",
    en: "Language, map layers, and the intel card stay as you left them.",
    tc: "語言、地圖圖層和情報欄會保持你上次的選擇。",
    sc: "语言、地图图层和情报栏会保持你上次的选择。",
  },
  {
    id: "2026-10-04-heading",
    date: "2026-10-04",
    kind: "added",
    en: "Trains and ferries show where they are heading.",
    tc: "列車和渡輪顯示前往的地點。",
    sc: "列车和渡轮显示前往的地点。",
  },
  {
    id: "2026-10-04-stops",
    date: "2026-10-04",
    kind: "fixed",
    en: "Opening a stop shows the published arrival times. Choosing Boundary opens a control point that is open.",
    tc: "打開一站，會顯示已公布的到站時間。選擇管制站時，會前往開放的管制站。",
    sc: "打开一站，会显示已公布的到站时间。选择管制站时，会前往开放的管制站。",
  },
  {
    id: "2026-10-03-bus-direction",
    date: "2026-10-03",
    kind: "fixed",
    en: "When a bus operator publishes where a bus is going, that destination is written on the stop sign. Nearby signs no longer cover one another.",
    tc: "巴士營運商有公布目的地時，站牌會寫上該班車前往的地點。相近的站牌不再疊在一起。",
    sc: "巴士营运商有公布目的地时，站牌会写上该班车前往的地点。相近的站牌不再叠在一起。",
  },
  {
    id: "2026-10-03-harbour-from",
    date: "2026-10-03",
    kind: "improved",
    en: "The three harbour times are compared from the same roadside sign, the one nearest the map. You can choose another sign.",
    tc: "三條過海時間以同一個路口比較，預設是地圖上最近的路口，也可以另選起點。",
    sc: "三条过海时间以同一个路口比较，预设是地图上最近的路口，也可以另选起点。",
  },
  {
    id: "2026-10-03-gmb-dest",
    date: "2026-10-03",
    kind: "added",
    en: "A green minibus card shows where that minibus is going.",
    tc: "綠色專線小巴卡片顯示小巴前往的地點。",
    sc: "绿色专线小巴卡片显示小巴前往的地点。",
  },
  {
    id: "2026-10-03-satellite",
    date: "2026-10-03",
    kind: "improved",
    en: "The satellite picture on a phone is sharper.",
    tc: "手機上的衛星圖更清晰。",
    sc: "手机上的卫星图更清晰。",
  },
  {
    id: "2026-10-03-top-bar",
    date: "2026-10-03",
    kind: "improved",
    en: "On a phone, the top bar is one line. The tunnel times, weather, and speed stay on that line, clear of the map buttons.",
    tc: "在手機上，頂欄是一行。隧道時間、天氣和車速都在這一行，不會被地圖按鈕擋住。",
    sc: "在手机上，顶栏是一行。隧道时间、天气和车速都在这一行，不会被地图按钮挡住。",
  },
  {
    id: "2026-10-03-ferry-channel",
    date: "2026-10-03",
    kind: "fixed",
    en: "A ferry without a published position follows the harbour and the sea channel, instead of a straight line across Hong Kong Island.",
    tc: "沒有公布船位的渡輪，沿海港和航道顯示，不再以直線橫過香港島。",
    sc: "没有公布船位的渡轮，沿海港和航道显示，不再以直线横过香港岛。",
  },
  {
    id: "2026-10-03-ferry-move",
    date: "2026-10-03",
    kind: "added",
    en: "Ferries that do not publish a boat position are drawn on the crossing and move with the sailing time.",
    tc: "沒有公布船位的渡輪，會按開出和到達時間在航道上移動。",
    sc: "没有公布船位的渡轮，会按开出和到达时间在航道上移动。",
  },
  {
    id: "2026-10-03-ferry-gps",
    date: "2026-10-03",
    kind: "fixed",
    en: "When Sun Ferry publishes a boat position, the map uses that position.",
    tc: "新渡輪公布船位時，地圖使用該船位。",
    sc: "新渡轮公布船位时，地图使用该船位。",
  },
  {
    id: "2026-10-03-tsuen-wan",
    date: "2026-10-03",
    kind: "fixed",
    en: "Tsuen Wan line trains are shown with the other MTR lines.",
    tc: "荃灣綫列車與其他港鐵綫一同顯示。",
    sc: "荃湾线列车与其他港铁线一同显示。",
  },
  {
    id: "2026-10-03-arrivals",
    date: "2026-10-03",
    kind: "improved",
    en: "Bus and ferry arrival times keep updating while several feeds are open.",
    tc: "同時開啟多項到站資料時，巴士和渡輪的到站時間仍會更新。",
    sc: "同时开启多项到站资料时，巴士和渡轮的到站时间仍会更新。",
  },
  {
    id: "2026-10-02-places",
    date: "2026-10-02",
    kind: "added",
    en: "Green minibuses, New Lantao buses, and ferry piers are on the map.",
    tc: "地圖加入綠色專線小巴、嶼巴和渡輪碼頭。",
    sc: "地图加入绿色专线小巴、屿巴和渡轮码头。",
  },
  {
    id: "2026-10-02-sun",
    date: "2026-10-02",
    kind: "added",
    en: "Every Sun Ferry route in the public arrival feed is included, with the inter-island boats.",
    tc: "公開到站資料中的新渡輪航線都已加入，包括橫水渡。",
    sc: "公开到站资料中的新渡轮航线都已加入，包括横水渡。",
  },
  {
    id: "2026-10-02-fortune",
    date: "2026-10-02",
    kind: "added",
    en: "The Fortune Ferry timetable for North Point and Kwun Tong is shown, and marked as a timetable.",
    tc: "北角和觀塘的富裕小輪船期已顯示，並註明是船期。",
    sc: "北角和观塘的富裕小轮船期已显示，并注明是船期。",
  },
  {
    id: "2026-10-02-systems",
    date: "2026-10-02",
    kind: "added",
    en: "This card has a systems list for a feed that does not load.",
    tc: "情報卡加入系統分頁，列出未能讀取的資料。",
    sc: "情报卡加入系统分页，列出未能读取的资料。",
  },
  {
    id: "2026-10-02-ferry-place",
    date: "2026-10-02",
    kind: "fixed",
    en: "A ferry card names where the boat is going, or where it is coming from.",
    tc: "渡輪卡片顯示船隻前往或駛來的地點。",
    sc: "渡轮卡片显示船只前往或驶来的地点。",
  },
  {
    id: "2026-10-02-berths",
    date: "2026-10-02",
    kind: "fixed",
    en: "Ferry pier pins sit on the passenger berths.",
    tc: "渡輪碼頭標記放在乘客碼頭的位置。",
    sc: "渡轮码头标记放在乘客码头的位置。",
  },
  {
    id: "2026-10-02-nlb",
    date: "2026-10-02",
    kind: "fixed",
    en: "New Lantao Bus arrival times use the Hong Kong clock.",
    tc: "嶼巴到站時間按香港時間顯示。",
    sc: "屿巴到站时间按香港时间显示。",
  },
  {
    id: "2026-10-02-gmb-zoom",
    date: "2026-10-02",
    kind: "improved",
    en: "Green minibus stops appear when the map is close enough to read them.",
    tc: "地圖放大至足以閱讀時，才顯示綠色專線小巴車站。",
    sc: "地图放大至足以阅读时，才显示绿色专线小巴车站。",
  },
  {
    id: "2026-10-02-routes",
    date: "2026-10-02",
    kind: "improved",
    en: "A stop still lists its routes when no arrival time is published.",
    tc: "車站未有到站時間時，仍會列出路線編號。",
    sc: "车站未有到站时间时，仍会列出路线编号。",
  },
  {
    id: "2026-10-02-crossing",
    date: "2026-10-02",
    kind: "fixed",
    en: "A harbour crossing with no published time is left off the bar.",
    tc: "沒有公布時間的過海航程不會出現在頂欄。",
    sc: "没有公布时间的过海航程不会出现在顶栏。",
  },
  {
    id: "2026-10-02-lrt",
    date: "2026-10-02",
    kind: "added",
    en: "Light Rail routes are drawn, and each train moves from the published minutes.",
    tc: "輕鐵路線畫在地圖上，列車按已公布的分鐘移動。",
    sc: "轻铁路线画在地图上，列车按已公布的分钟移动。",
  },
  {
    id: "2026-10-02-citybus",
    date: "2026-10-02",
    kind: "added",
    en: "Citybus stops show the published arrival when the map is close.",
    tc: "地圖拉近後，城巴車站顯示已公布的到站時間。",
    sc: "地图拉近后，城巴车站显示已公布的到站时间。",
  },
  {
    id: "2026-10-01-kmb",
    date: "2026-10-01",
    kind: "added",
    en: "A KMB stop card lists the arrivals the operator has published.",
    tc: "九巴車站卡片列出營運商已公布的到站班次。",
    sc: "九巴车站卡片列出营运商已公布的到站班次。",
  },
  {
    id: "2026-10-01-mtr",
    date: "2026-10-01",
    kind: "added",
    en: "MTR trains move along the line from the minutes published for the next train.",
    tc: "港鐵列車按已公布的下一班車分鐘，沿路線移動。",
    sc: "港铁列车按已公布的下一班车分钟，沿路线移动。",
  },
  {
    id: "2026-09-30-camera",
    date: "2026-09-30",
    kind: "improved",
    en: "A street camera card names the place the camera looks at.",
    tc: "街道快拍卡片寫明鏡頭所在的地點。",
    sc: "街道快拍卡片写明镜头所在的地点。",
  },
  {
    id: "2026-09-30-phone",
    date: "2026-09-30",
    kind: "improved",
    en: "On a phone, the top bar can be hidden so the map has the screen.",
    tc: "在手機上，頂欄可以收起，把畫面留給地圖。",
    sc: "在手机上，顶栏可以收起，把画面留给地图。",
  },
  {
    id: "2026-09-29-roads",
    date: "2026-09-29",
    kind: "improved",
    en: "Road colour follows the Transport Department grades of Good, Average, and Bad.",
    tc: "道路顏色沿用運輸署的暢順、緩慢和擠塞等級。",
    sc: "道路颜色沿用运输署的畅顺、缓慢和挤塞等级。",
  },
  {
    id: "2026-09-29-boundary",
    date: "2026-09-29",
    kind: "added",
    en: "The land boundary control points show the passenger halls.",
    tc: "陸路管制站顯示旅客大堂的輪候。",
    sc: "陆路管制站显示旅客大堂的轮候。",
  },
  {
    id: "2026-09-29-chinese",
    date: "2026-09-29",
    kind: "added",
    en: "The map opens in Traditional Chinese.",
    tc: "地圖以繁體中文開啟。",
    sc: "地图以繁体中文开启。",
  },
  {
    id: "2026-09-28-picture",
    date: "2026-09-28",
    kind: "added",
    en: "The map has a satellite picture, a street map, and a buildings view.",
    tc: "地圖有衛星圖、街道圖和樓宇視角。",
    sc: "地图有卫星图、街道图和楼宇视角。",
  },
  {
    id: "2026-09-28-roads",
    date: "2026-09-28",
    kind: "added",
    en: "Cameras, road works, toll points, and traffic notices sit on the strategic roads, with the live speed.",
    tc: "快拍、道路工程、收費點和交通消息放在策略性道路上，並顯示車速。",
    sc: "快拍、道路工程、收费点和交通消息放在策略性道路上，并显示车速。",
  },
  {
    id: "2026-09-28-harbour",
    date: "2026-09-28",
    kind: "added",
    en: "The three harbour crossings show the live minutes.",
    tc: "三條過海隧道顯示實時分鐘。",
    sc: "三条过海隧道显示实时分钟。",
  },
]

export function changelogText(entry: ChangelogEntry, locale: Locale): string {
  switch (locale) {
    case "en":
      return entry.en
    case "zh-CN":
      return entry.sc
    case "zh-HK":
      return entry.tc
    default: {
      const exhaustive: never = locale
      return exhaustive
    }
  }
}
